"""drop column hello from users

Revision ID: 2c851f1fc347
Revises: fd77f22539b6
Create Date: 2025-08-20 17:05:07.530820

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c851f1fc347'
down_revision: Union[str, Sequence[str], None] = 'fd77f22539b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'hello')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hello', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
